#!/bin/bash
set -ue -o pipefail
export LC_ALL=C

###
# gce/el8.startup.sh
# https://github.com/furplag/cogman
# Copyright 2019+ furplag
# Licensed under MIT (https://github.com/furplag/cogman/blob/main/LICENSE)
#
# scripts on startup, shutdown and initial settings to virtual machines,
# maybe useful for poor man like me, but currently just only for me own .
#
# 1.  Server initial setting (do only first time) .
#   1.  makes some optimizations for the VM to stands a web server .
#     - i18N (Locale / Language) setting .
#     - l10N (Timezone) setting .
#     - unforcing SELinux .
#   2.  change SSH port number for protect under crack .
#     - Firewall setting (firewalld) .
#     - SSH port number setting (sshd) .
#
#       | setting | change to |
#       |----|----|
#       | Port | the port number you  decide to change . |
#       | PermitRootLogin | without-password |
#       | PubkeyAuthentication | yes |
#       | PasswordAuthentication | no |
#       | PermitEmptyPasswords | no |
#       | ChallengeResponseAuthentication | no |
#       | GSSAPIAuthentication | no |
#
#       - only use Public Key Authentication .
#       - enable to login as Root directly .
#     - generate SSH key pair .
#   3.  and never repeated .
# 2.  Server startup notification .

# variable
declare -r repo_url='https://raw.githubusercontent.com/furplag/cogman/main'
declare -r metadata_url='http://metadata.google.internal/computeMetadata/v1'
declare indent='\xF0\x9F\x91\xBB'

# install command `retrieve_metadata` .
if ! which retrieve_metadata >/dev/null 2>&1; then bash <(curl "${repo_url}/gce/install.retrieve_metadata.sh" -LfsS); fi

# install command `is_preempted` .
if ! which is_preempted >/dev/null 2>&1; then bash <(curl "${repo_url}/gce/install.is_preempted.sh" -LfsS); fi

###
# variable

# vars of server initial setting
declare -r locale_lang=$(retrieve_metadata 'locale')
declare -r timezone=$(retrieve_metadata 'timezone')
declare -r ssh_port_number=$(retrieve_metadata 'ssh-port')
declare -r ssh_key_passphrase=$(retrieve_metadata 'ssh-key-passphrase')
declare -r ssh_keygen_options=$(retrieve_metadata 'ssh-keygen-options' '-t ed25519')

# vars of server status notification using IFTTT
declare -r ifttt_api_key=$(retrieve_metadata 'ifttt-api-key')
declare -r platform="GCE ($(retrieve_metadata 'zone' 'Unknown' | sed -e 's/^.*\///')) "
declare -r project=$(retrieve_metadata 'project-id' 'Unknown')
declare -r instance=$(retrieve_metadata 'name' "$(hostname)")

# vars of server status notification using Slack and HUBOT
declare -r slackbot_user=$(retrieve_metadata 'slackbot-user' 'shockwave')
declare -r slackbot_group=$(retrieve_metadata 'slackbot-group' 'decepticons')
declare -ir slackbot_uid=$(retrieve_metadata 'slackbot-uid' 1101)
declare -ir slackbot_gid=$(retrieve_metadata 'slackbot-gid' 1111)
declare -r slackbot_hubot_token=$(retrieve_metadata 'slackbot-hubot-token')
declare -r slackbot_hubot_domain=$(retrieve_metadata 'slackbot-hubot-domain' 'example.com')
declare -r slackbot_hubot_dir=$(retrieve_metadata 'slackbot-hubot-dir' "/home/${slackbot_user}/hubot-${slackbot_user}")
declare -r slackbot_hubot_name=$(retrieve_metadata 'slackbot-hubot-name' "slackbot-${slackbot_user}")
declare -r slackbot_hubot_desc=$(retrieve_metadata 'slackbot-hubot-desc' 'server status notifierer generated by Cogman .')
declare -r slackbot_hubot_owner=$(retrieve_metadata 'slackbot-hubot-owner' "${slackbot_user} ${slackbot_user}.${project,,}.${platform,,}@${slackbot_hubot_domain}")

source <(curl "${repo_url}/el8.startup.sh" -fLsS)
