#!/bin/bash
set -ue -o pipefail
export LC_ALL=C

###
# gce/is_preempted
# https://github.com/furplag/cogman
# Copyright 2019+ furplag
# Licensed under MIT (https://github.com/furplag/cogman/blob/main/LICENSE)
#
# detects whether this server getting under preempted or not .
# see also https://cloud.google.com/compute/docs/instances/preemptible .

###
# variable
if ! declare -p repo_url >/dev/null 2>&1; then declare -r repo_url='https://raw.githubusercontent.com/furplag/cogman/main'; fi


###
# functions

###
# tests if this server getting under preempted .
#
# @return the result
function _is_preempted() {
  local _filter="targetId=$(retrieve_metadata id 'none')"
  _filter="${_filter} AND operationType='compute.instances.preempted'"
  _filter="${_filter} AND insertTime>-Pt10m"
  local -i _result=1

  if ! which gcloud >/dev/null 2>&1; then :;
  elif ! which retrieve_metadata >/dev/null 2>&1; then :;
  elif [[ $(gcloud compute operations list --filter="${_filter}" --sort-by=~insertTime --limit=10 | wc -l) -gt 0 ]]; then _result=0; fi

  return $_result;
}

if ! which retrieve_metadata >/dev/null 2>&1; then bash <(curl "${repo_url}/gce/install.retrieve_metadata.sh" -LfsS); fi

_is_preempted >/dev/null 2>&1

